### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by simontombu** [hundun000/mirai-fleet-amiya#2]
2022-06-24 17:46:48 E/hundun.fleet.amiya: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
        at mirai-fleet-amiya-0.2.3.mirai.jar//com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at mirai-fleet-amiya-0.2.3.mirai.jar//com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
        at mirai-fleet-amiya-0.2.3.mirai.jar//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
        at mirai-fleet-amiya-0.2.3.mirai.jar//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3453)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.framework.core.helper.repository.FileRepository.readFile(FileRepository.java:96)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.framework.core.helper.repository.FileRepository.<init>(FileRepository.java:65)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.framework.core.helper.repository.MapDocumentRepository.<init>(MapDocumentRepository.java:46)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.framework.starter.botlogic.function.weibo.db.TopCardInfoRepository.<init>(TopCardInfoRepository.java:22)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.framework.starter.botlogic.function.weibo.WeiboFunction.<init>(WeiboFunction.java:88)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.arknights.amiya.botlogic.AmiyaBotLogic.<init>(AmiyaBotLogic.java:46)
        at mirai-fleet-amiya-0.2.3.mirai.jar//hundun.miraifleet.arknights.amiya.AmiyaPlugin.onEnable(AmiyaPlugin.java:34)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:119)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:262)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:34)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:183)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:231)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

**Comment by hundun000** [comment]
看看`data/hundun.fleet.amiya/WeiboFunction/repositories/TopCardInfoRepository.json`现在内容是什么

**Comment by simontombu** [comment]
> 看看`data/hundun.fleet.amiya/WeiboFunction/repositories/TopCardInfoRepository.json`现在内容是什么

空白，没东西

**Comment by hundun000** [comment]
那删掉文件应该能解决。空白原因可能是极小概率写入途中重启了吧。

**Comment by simontombu** [comment]
> 那删掉文件应该能解决。空白原因可能是极小概率写入途中重启了吧。

删了之后问题解决了，原来里边应该自动生成个{}
不知道为啥，最近也没重启服务器来着，大抵是脸黑吧
